% TEST_STOKES_SQUARE_GRADUEX: gradient of the exact solution.

function gu = test_stokes_square_graduex (x, y)
  uxx = @(x, y) (4.*exp(x).*(-1+x).^2.*x.*(-1+y).*y.*(-1+2.*y)+ ...
                 4.*exp(x).*(-1+x).*x.^2.*(-1+y).*y.*(-1+2.*y)+ ...
                 2.*exp(x).*(-1+x).^2.*x.^2.*(-1+y).*y.*(-1+2.*y));
  
  uxy = @(x, y) (4.*exp(x).*(-1+x).^2.*x.^2.*(-1+y).*y+ ...
                 2.*exp(x).*(-1+x).^2.*x.^2.*(-1+y).*(-1+2.*y)+ ...
                 2.*exp(x).*(-1+x).^2.*x.^2.*y.*(-1+2.*y));
  
  uyx = @(x, y) (-exp(x).*(-1+x).*x.*(3+2.*x).*(-1+y).^2.*y.^2- ...
                 exp(x).*(-1+x).*(-2+x.*(3+x)).*(-1+y).^2.*y.^2- ...
                 exp(x).*x.*(-2+x.*(3+x)).*(-1+y).^2.*y.^2- ...
                 exp(x).*(-1+x).*x.*(-2+x.*(3+x)).*(-1+y).^2.*y.^2);
  
  uyy = @(x, y) (-2.*exp(x).*(-1+x).*x.*(-2+x.*(3+x)).*(-1+y).^2.*y- ...
                 2.*exp(x).*(-1+x).*x.*(-2+x.*(3+x)).*(-1+y).*y.^2);
  
  gu = zeros (2, 2, size(x,1), size(x,2));
  gu(1, 1, :, :) = reshape (uxx (x,y), [1, 1, size(x)]);
  gu(2, 1, :, :) = reshape (uyx (x,y), [1, 1, size(x)]);
  gu(1, 2, :, :) = reshape (uxy (x,y), [1, 1, size(x)]);
  gu(2, 2, :, :) = reshape (uyy (x,y), [1, 1, size(x)]);
end
